### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by nitrag** [JacisNonsense/DellIPMIFanCtrl#1]
Need to add usage of commands to Readme. I'm not familiar with Ruby.

```
ruby fanctrl.rb
fanctrl.rb:27:in `get_fan_speed': undefined method `[]' for nil:NilClass (NoMethodError)
	from fanctrl.rb:49:in `block in <main>'
	from fanctrl.rb:46:in `loop'
	from fanctrl.rb:46:in `<main>'
```

**Comment by JaciBrunning** [comment]
Should be fixed now!

**Comment by nitrag** [comment]
Can you provide instructions on how to setup the device?

`Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory`

**Comment by JaciBrunning** [comment]
Those files should already be present if you have `ipmitool` installed and IPMI enabled in the iDRAC POST menu. There shouldn't be any other steps in the setup for a clean linux install
